// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformAPI.Data;

#nullable disable

namespace PlatformAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714043657_AddInchAndMillimeterToUnitsTable")]
    partial class AddInchAndMillimeterToUnitsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlatformAPI.Models.Recipe.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsMine")
                        .HasColumnType("bit");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("PlatformAPI.Models.Recipe.FractionDecimal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("Decimal")
                        .HasColumnType("real");

                    b.Property<string>("Fraction")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Primary")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FractionDecimals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Decimal = 0.0625f,
                            Fraction = "1/16",
                            Primary = true
                        },
                        new
                        {
                            Id = 2,
                            Decimal = 0.125f,
                            Fraction = "1/8",
                            Primary = true
                        },
                        new
                        {
                            Id = 3,
                            Decimal = 0.1875f,
                            Fraction = "3/16",
                            Primary = true
                        },
                        new
                        {
                            Id = 4,
                            Decimal = 0.25f,
                            Fraction = "1/4",
                            Primary = true
                        },
                        new
                        {
                            Id = 5,
                            Decimal = 0.3125f,
                            Fraction = "5/16",
                            Primary = true
                        },
                        new
                        {
                            Id = 6,
                            Decimal = 0.375f,
                            Fraction = "3/8",
                            Primary = true
                        },
                        new
                        {
                            Id = 7,
                            Decimal = 0.4375f,
                            Fraction = "7/16",
                            Primary = true
                        },
                        new
                        {
                            Id = 8,
                            Decimal = 0.5f,
                            Fraction = "1/2",
                            Primary = true
                        },
                        new
                        {
                            Id = 9,
                            Decimal = 0.5625f,
                            Fraction = "9/16",
                            Primary = true
                        },
                        new
                        {
                            Id = 10,
                            Decimal = 0.625f,
                            Fraction = "5/8",
                            Primary = true
                        },
                        new
                        {
                            Id = 11,
                            Decimal = 0.6875f,
                            Fraction = "11/16",
                            Primary = true
                        },
                        new
                        {
                            Id = 12,
                            Decimal = 0.75f,
                            Fraction = "3/4",
                            Primary = true
                        },
                        new
                        {
                            Id = 13,
                            Decimal = 0.8125f,
                            Fraction = "13/16",
                            Primary = true
                        },
                        new
                        {
                            Id = 14,
                            Decimal = 0.875f,
                            Fraction = "7/8",
                            Primary = true
                        },
                        new
                        {
                            Id = 15,
                            Decimal = 0.9375f,
                            Fraction = "15/16",
                            Primary = true
                        },
                        new
                        {
                            Id = 16,
                            Decimal = 0.25f,
                            Fraction = "4/16",
                            Primary = false
                        },
                        new
                        {
                            Id = 17,
                            Decimal = 0.125f,
                            Fraction = "2/16",
                            Primary = false
                        },
                        new
                        {
                            Id = 18,
                            Decimal = 0.375f,
                            Fraction = "6/16",
                            Primary = false
                        },
                        new
                        {
                            Id = 19,
                            Decimal = 0.5f,
                            Fraction = "8/16",
                            Primary = false
                        },
                        new
                        {
                            Id = 20,
                            Decimal = 0.625f,
                            Fraction = "10/16",
                            Primary = false
                        },
                        new
                        {
                            Id = 21,
                            Decimal = 0.75f,
                            Fraction = "12/16",
                            Primary = false
                        },
                        new
                        {
                            Id = 22,
                            Decimal = 0.875f,
                            Fraction = "14/16",
                            Primary = false
                        },
                        new
                        {
                            Id = 23,
                            Decimal = 0.25f,
                            Fraction = "2/8",
                            Primary = false
                        },
                        new
                        {
                            Id = 24,
                            Decimal = 0.5f,
                            Fraction = "4/8",
                            Primary = false
                        },
                        new
                        {
                            Id = 25,
                            Decimal = 0.75f,
                            Fraction = "6/8",
                            Primary = false
                        },
                        new
                        {
                            Id = 26,
                            Decimal = 0.5f,
                            Fraction = "2/4",
                            Primary = false
                        },
                        new
                        {
                            Id = 27,
                            Decimal = 0.333f,
                            Fraction = "1/3",
                            Primary = true
                        },
                        new
                        {
                            Id = 28,
                            Decimal = 0.667f,
                            Fraction = "2/3",
                            Primary = true
                        },
                        new
                        {
                            Id = 29,
                            Decimal = 0.2f,
                            Fraction = "1/5",
                            Primary = true
                        },
                        new
                        {
                            Id = 30,
                            Decimal = 0.4f,
                            Fraction = "2/5",
                            Primary = true
                        },
                        new
                        {
                            Id = 31,
                            Decimal = 0.6f,
                            Fraction = "3/5",
                            Primary = true
                        },
                        new
                        {
                            Id = 32,
                            Decimal = 0.8f,
                            Fraction = "4/5",
                            Primary = true
                        });
                });

            modelBuilder.Entity("PlatformAPI.Models.Recipe.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Instructions")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<float?>("Quantity")
                        .HasColumnType("real");

                    b.Property<float?>("QuantityMax")
                        .HasColumnType("real");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("PlatformAPI.Models.Recipe.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RecipeFont")
                        .HasColumnType("int");

                    b.Property<int>("RecipeVisibility")
                        .HasColumnType("int");

                    b.Property<bool>("ShowAbbreviations")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("PlatformAPI.Models.Recipe.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId")
                        .IsUnique();

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("PlatformAPI.Models.Recipe.RecipeStep", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("StepId")
                        .HasColumnType("int");

                    b.HasKey("RecipeId", "StepId");

                    b.HasIndex("StepId")
                        .IsUnique();

                    b.ToTable("RecipeSteps");
                });

            modelBuilder.Entity("PlatformAPI.Models.Recipe.Step", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("PlatformAPI.Models.Recipe.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Plural")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("System")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "lb",
                            Description = "pound",
                            Plural = "pounds",
                            System = 1
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "oz",
                            Description = "ounce",
                            Plural = "ounces",
                            System = 1
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "gal",
                            Description = "gallon",
                            Plural = "gallons",
                            System = 1
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "qt",
                            Description = "quart",
                            Plural = "quarts",
                            System = 1
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "pt",
                            Description = "pint",
                            Plural = "pints",
                            System = 1
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "fl oz",
                            Description = "fluid ounce",
                            Plural = "fluid ounces",
                            System = 1
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "Tbsp",
                            Description = "tablespoon",
                            Plural = "tablespoons",
                            System = 1
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "tsp",
                            Description = "teaspoon",
                            Plural = "teaspoons",
                            System = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "can",
                            Plural = "cans"
                        },
                        new
                        {
                            Id = 11,
                            Description = "cup",
                            Plural = "cups",
                            System = 1
                        },
                        new
                        {
                            Id = 12,
                            Abbreviation = "ml",
                            Description = "milliliter",
                            Plural = "milliliters",
                            System = 2
                        },
                        new
                        {
                            Id = 13,
                            Abbreviation = "L",
                            Description = "liter",
                            Plural = "liters",
                            System = 2
                        },
                        new
                        {
                            Id = 14,
                            Abbreviation = "g",
                            Description = "gram",
                            Plural = "grams",
                            System = 2
                        },
                        new
                        {
                            Id = 15,
                            Abbreviation = "kg",
                            Description = "kilogram",
                            Plural = "kilograms",
                            System = 2
                        },
                        new
                        {
                            Id = 16,
                            Abbreviation = "cm",
                            Description = "centimeter",
                            Plural = "centimeters",
                            System = 2
                        },
                        new
                        {
                            Id = 17,
                            Description = "pinch",
                            Plural = "pinch"
                        },
                        new
                        {
                            Id = 18,
                            Description = "clove",
                            Plural = "cloves"
                        },
                        new
                        {
                            Id = 19,
                            Description = "piece",
                            Plural = "pieces"
                        },
                        new
                        {
                            Id = 20,
                            Description = "stick",
                            Plural = "sticks"
                        },
                        new
                        {
                            Id = 21,
                            Description = "drop",
                            Plural = "drops"
                        },
                        new
                        {
                            Id = 22,
                            Description = "slice",
                            Plural = "slices"
                        },
                        new
                        {
                            Id = 23,
                            Description = "dash",
                            Plural = "dash"
                        },
                        new
                        {
                            Id = 24,
                            Description = "inch",
                            Plural = "inches",
                            System = 1
                        },
                        new
                        {
                            Id = 25,
                            Abbreviation = "mm",
                            Description = "millimeter",
                            Plural = "millimeters",
                            System = 2
                        });
                });

            modelBuilder.Entity("PlatformAPI.Models.Recipe.UserRecipe", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RecipeId");

                    b.HasIndex("RecipeId")
                        .IsUnique();

                    b.ToTable("UserRecipes");
                });

            modelBuilder.Entity("PlatformAPI.Models.Themes.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Themes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Light Blue",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dark",
                            IsActive = false,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dark Teal",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Light Green",
                            IsActive = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Dark Green",
                            IsActive = true,
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("PlatformAPI.Models.Themes.ThemeVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ThemeVariables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "dropdownBackColor",
                            GroupId = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "dropdownTextColor",
                            GroupId = 1,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 3,
                            Description = "dropdownHoverBackColor",
                            GroupId = 1,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 4,
                            Description = "dropdownHoverTextColor",
                            GroupId = 1,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 5,
                            Description = "dropdownContentBackgroundColor",
                            GroupId = 1,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 6,
                            Description = "dropdownContentTextColor",
                            GroupId = 1,
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 7,
                            Description = "textBoxLabelColor",
                            GroupId = 2,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "buttonBackgroundColor",
                            GroupId = 3,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "buttonTextColor",
                            GroupId = 3,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "buttonHoverBackgroundColor",
                            GroupId = 3,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 11,
                            Description = "buttonHoverTextColor",
                            GroupId = 3,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 12,
                            Description = "contentBackColor",
                            GroupId = 4,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 13,
                            Description = "textBoxTextColor",
                            GroupId = 2,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 14,
                            Description = "textBoxBackColor",
                            GroupId = 2,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 15,
                            Description = "outsideBackColor",
                            GroupId = 5,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 16,
                            Description = "textBoxBorderColor",
                            GroupId = 2,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 17,
                            Description = "dropdownBackColorGradient",
                            GroupId = 1,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 18,
                            Description = "dropdownHoverBackColorGradient",
                            GroupId = 1,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 19,
                            Description = "dropdownContentBackgroundColorGradient",
                            GroupId = 1,
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 20,
                            Description = "buttonBackgroundColorGradient",
                            GroupId = 3,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 21,
                            Description = "buttonHoverBackgroundColorGradient",
                            GroupId = 3,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 22,
                            Description = "contentBackColorGradient",
                            GroupId = 4,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 23,
                            Description = "textBoxBackColorGradient",
                            GroupId = 2,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 24,
                            Description = "outsideBackColorGradient",
                            GroupId = 5,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 25,
                            Description = "contentHeaderBackColor",
                            GroupId = 7,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 26,
                            Description = "contentHeaderBackColorGradient",
                            GroupId = 7,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 27,
                            Description = "contentHeaderTextColor",
                            GroupId = 7,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 28,
                            Description = "contentTextColor",
                            GroupId = 7,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 29,
                            Description = "linkTextColor",
                            GroupId = 7,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 30,
                            Description = "radioLabelColor",
                            GroupId = 8,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 31,
                            Description = "radioHoverColor",
                            GroupId = 8,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 32,
                            Description = "radioCheckColor",
                            GroupId = 8,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 33,
                            Description = "dialogHeaderBackColor",
                            GroupId = 9,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 34,
                            Description = "dialogHeaderBackColorGradient",
                            GroupId = 9,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 35,
                            Description = "dialogHeaderTextColor",
                            GroupId = 9,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 36,
                            Description = "dialogContentBackColor",
                            GroupId = 9,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 37,
                            Description = "dialogContentBackColorGradient",
                            GroupId = 9,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 38,
                            Description = "dialogContentTextColor",
                            GroupId = 9,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 39,
                            Description = "sortableBorder",
                            GroupId = 10,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 40,
                            Description = "sortableHighlightBackColor",
                            GroupId = 10,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 41,
                            Description = "sortableHighlightBackColorGradient",
                            GroupId = 10,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 42,
                            Description = "textBoxBorderColorSelected",
                            GroupId = 2,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 43,
                            Description = "passwordIconColor",
                            GroupId = 2,
                            SortOrder = 7
                        });
                });

            modelBuilder.Entity("PlatformAPI.Models.Themes.ThemeVariableColor", b =>
                {
                    b.Property<int>("ThemeId")
                        .HasColumnType("int");

                    b.Property<int>("ThemeVariableId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ThemeId", "ThemeVariableId");

                    b.HasIndex("ThemeVariableId");

                    b.ToTable("ThemeVariablesColors");

                    b.HasData(
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 1,
                            Color = "#0058f2"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 2,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 3,
                            Color = "#0030a0"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 4,
                            Color = "#FFFFFF"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 5,
                            Color = "#0058f2"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 6,
                            Color = "#FFFFFF"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 7,
                            Color = "#0048d1"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 8,
                            Color = "#0058f2"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 9,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 10,
                            Color = "#0030a0"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 11,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 12,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 13,
                            Color = "#000000"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 14,
                            Color = "#A0C2FF"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 15,
                            Color = "#f3f5f7"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 16,
                            Color = "#0000ee"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 17,
                            Color = "#3178dd"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 18,
                            Color = "#0042b8"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 19,
                            Color = "#3178dd"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 20,
                            Color = "#3178dd"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 21,
                            Color = "#0042b8"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 22,
                            Color = "#efefef"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 23,
                            Color = "#78AFFF"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 24,
                            Color = "#e3e5e7"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 25,
                            Color = "#0054ff"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 26,
                            Color = "#1074ef"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 27,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 28,
                            Color = "#0038a1"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 29,
                            Color = "#0038a1"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 30,
                            Color = "#0048d1"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 31,
                            Color = "#003cb5"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 32,
                            Color = "#0048d1"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 33,
                            Color = "#0054ff"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 34,
                            Color = "#1074ef"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 35,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 36,
                            Color = "#c3c5c7"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 37,
                            Color = "#b3b5b7"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 38,
                            Color = "#00143f"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 39,
                            Color = "#0048d1"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 40,
                            Color = "#0048d1"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 41,
                            Color = "#0058f2"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 42,
                            Color = "#101010"
                        },
                        new
                        {
                            ThemeId = 1,
                            ThemeVariableId = 43,
                            Color = "#000000"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 1,
                            Color = "#131210"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 2,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 3,
                            Color = "#050302"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 4,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 5,
                            Color = "#1f1e1c"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 6,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 7,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 8,
                            Color = "#131210"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 9,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 10,
                            Color = "#050302"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 11,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 12,
                            Color = "#343434"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 13,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 14,
                            Color = "#141414"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 15,
                            Color = "#0c0a08"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 16,
                            Color = "#18b5ea"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 17,
                            Color = "#232220"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 18,
                            Color = "#151312"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 19,
                            Color = "#2f2e2c"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 20,
                            Color = "#232220"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 21,
                            Color = "#151312"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 22,
                            Color = "#444444"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 23,
                            Color = "#242424"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 24,
                            Color = "#1c1a18"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 25,
                            Color = "#131210"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 26,
                            Color = "#232220"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 27,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 28,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 29,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 30,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 31,
                            Color = "#bbbbbb"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 32,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 33,
                            Color = "#131210"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 34,
                            Color = "#232220"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 35,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 36,
                            Color = "#acaaa8"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 37,
                            Color = "#bcbab8"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 38,
                            Color = "#000000"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 39,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 40,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 41,
                            Color = "#dfdfdf"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 42,
                            Color = "#FFFFFF"
                        },
                        new
                        {
                            ThemeId = 2,
                            ThemeVariableId = 43,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 1,
                            Color = "#0B5257"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 2,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 3,
                            Color = "#0E3733"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 4,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 5,
                            Color = "#0B5257"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 6,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 7,
                            Color = "#00B0A0"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 8,
                            Color = "#0B5257"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 9,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 10,
                            Color = "#0E2723"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 11,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 12,
                            Color = "#000000"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 13,
                            Color = "#00B0A0"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 14,
                            Color = "#0B4A4F"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 15,
                            Color = "#0C0A08"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 16,
                            Color = "#18b5ea"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 17,
                            Color = "#123D3A"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 18,
                            Color = "#0E3733"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 19,
                            Color = "#1A3F3A"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 20,
                            Color = "#1A3F3A"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 21,
                            Color = "#0E3733"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 22,
                            Color = "#101010"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 23,
                            Color = "#242424"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 24,
                            Color = "#1C1A18"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 25,
                            Color = "#0B5257"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 26,
                            Color = "#1A3F3A"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 27,
                            Color = "#00B8A8"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 28,
                            Color = "#00B0A0"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 29,
                            Color = "#00B0A0"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 30,
                            Color = "#00B0A0"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 31,
                            Color = "#006D5B"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 32,
                            Color = "#00B0A0"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 33,
                            Color = "#0B5257"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 34,
                            Color = "#1A3F3A"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 35,
                            Color = "#00B8A8"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 36,
                            Color = "#acaaa8"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 37,
                            Color = "#bcbab8"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 38,
                            Color = "#001205"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 39,
                            Color = "#008080"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 40,
                            Color = "#008080"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 41,
                            Color = "#20a295"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 42,
                            Color = "#FFFFFF"
                        },
                        new
                        {
                            ThemeId = 3,
                            ThemeVariableId = 43,
                            Color = "#00B0A0"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 1,
                            Color = "#009837"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 2,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 3,
                            Color = "#115543"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 4,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 5,
                            Color = "#00751F"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 6,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 7,
                            Color = "#009837"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 8,
                            Color = "#009837"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 9,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 10,
                            Color = "#115543"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 11,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 12,
                            Color = "#f7fffe"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 13,
                            Color = "#00321A"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 14,
                            Color = "#31C74D"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 15,
                            Color = "#fafefd"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 16,
                            Color = "#008000"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 17,
                            Color = "#10a847"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 18,
                            Color = "#107847"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 19,
                            Color = "#10a847"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 20,
                            Color = "#10a847"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 21,
                            Color = "#107847"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 22,
                            Color = "#e7efee"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 23,
                            Color = "#37B74D"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 24,
                            Color = "#eaeeed"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 25,
                            Color = "#009837"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 26,
                            Color = "#10a847"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 27,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 28,
                            Color = "#006327"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 29,
                            Color = "#006327"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 30,
                            Color = "#009837"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 31,
                            Color = "#006235"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 32,
                            Color = "#009837"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 33,
                            Color = "#009837"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 34,
                            Color = "#10a847"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 35,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 36,
                            Color = "#cacecd"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 37,
                            Color = "#babebd"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 38,
                            Color = "#003225"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 39,
                            Color = "#009837"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 40,
                            Color = "#009837"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 41,
                            Color = "#208255"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 42,
                            Color = "#101010"
                        },
                        new
                        {
                            ThemeId = 4,
                            ThemeVariableId = 43,
                            Color = "#00321A"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 1,
                            Color = "#0e7733"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 2,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 3,
                            Color = "#073411"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 4,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 5,
                            Color = "#0e7733"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 6,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 7,
                            Color = "#00BF73"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 8,
                            Color = "#0e7733"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 9,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 10,
                            Color = "#073411"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 11,
                            Color = "#ffffff"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 12,
                            Color = "#000000"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 13,
                            Color = "#00BF73"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 14,
                            Color = "#0C4D40"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 15,
                            Color = "#0c0a08"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 16,
                            Color = "#18aa45"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 17,
                            Color = "#184615"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 18,
                            Color = "#0F3510"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 19,
                            Color = "#184615"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 20,
                            Color = "#184615"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 21,
                            Color = "#0F3510"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 22,
                            Color = "#101010"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 23,
                            Color = "#242424"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 24,
                            Color = "#1c1a18"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 25,
                            Color = "#0e7733"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 26,
                            Color = "#184615"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 27,
                            Color = "#002225"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 28,
                            Color = "#00BF73"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 29,
                            Color = "#00BF73"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 30,
                            Color = "#00BF73"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 31,
                            Color = "#007235"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 32,
                            Color = "#00BF73"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 33,
                            Color = "#0e7733"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 34,
                            Color = "#184615"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 35,
                            Color = "#001A25"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 36,
                            Color = "#acaaa8"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 37,
                            Color = "#bcbab8"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 38,
                            Color = "#001A25"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 39,
                            Color = "#00BF73"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 40,
                            Color = "#00BF73"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 41,
                            Color = "#149F53"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 42,
                            Color = "#FFFFFF"
                        },
                        new
                        {
                            ThemeId = 5,
                            ThemeVariableId = 43,
                            Color = "#00BF73"
                        });
                });

            modelBuilder.Entity("PlatformAPI.Models.Users.ForgotPasswordRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Updated")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ForgotPasswordRequests");
                });

            modelBuilder.Entity("PlatformAPI.Models.Users.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "F",
                            Description = "Female"
                        },
                        new
                        {
                            Id = 2,
                            Code = "M",
                            Description = "Male"
                        },
                        new
                        {
                            Id = 3,
                            Code = "TG",
                            Description = "Transgender"
                        },
                        new
                        {
                            Id = 4,
                            Code = "NB",
                            Description = "Non-binary"
                        },
                        new
                        {
                            Id = 5,
                            Code = "X",
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("PlatformAPI.Models.Users.LoginAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoginAttempts", (string)null);
                });

            modelBuilder.Entity("PlatformAPI.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.Property<bool>("HasSelectedMeasurementSystem")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLegacyPassword")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LegacyPassword")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MeasurementSystem")
                        .HasColumnType("int");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Pronouns")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ThemeId")
                        .HasColumnType("int");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlatformAPI.Models.Users.UserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SA",
                            Description = "Super Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Code = "A",
                            Description = "Administrator"
                        },
                        new
                        {
                            Id = 3,
                            Code = "R",
                            Description = "Restaurant"
                        },
                        new
                        {
                            Id = 4,
                            Code = "S",
                            Description = "Standard User"
                        },
                        new
                        {
                            Id = 5,
                            Code = "G",
                            Description = "Guest User"
                        });
                });

            modelBuilder.Entity("PlatformAPI.Models.Recipe.Favorite", b =>
                {
                    b.HasOne("PlatformAPI.Models.Recipe.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlatformAPI.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlatformAPI.Models.Recipe.RecipeIngredient", b =>
                {
                    b.HasOne("PlatformAPI.Models.Recipe.Ingredient", null)
                        .WithOne("RecipeIngredient")
                        .HasForeignKey("PlatformAPI.Models.Recipe.RecipeIngredient", "IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlatformAPI.Models.Recipe.RecipeStep", b =>
                {
                    b.HasOne("PlatformAPI.Models.Recipe.Step", null)
                        .WithOne("RecipeStep")
                        .HasForeignKey("PlatformAPI.Models.Recipe.RecipeStep", "StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlatformAPI.Models.Recipe.UserRecipe", b =>
                {
                    b.HasOne("PlatformAPI.Models.Recipe.Recipe", null)
                        .WithOne("UserRecipe")
                        .HasForeignKey("PlatformAPI.Models.Recipe.UserRecipe", "RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlatformAPI.Models.Themes.ThemeVariableColor", b =>
                {
                    b.HasOne("PlatformAPI.Models.Themes.ThemeVariable", "ThemeVariable")
                        .WithMany()
                        .HasForeignKey("ThemeVariableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThemeVariable");
                });

            modelBuilder.Entity("PlatformAPI.Models.Users.LoginAttempt", b =>
                {
                    b.HasOne("PlatformAPI.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlatformAPI.Models.Users.User", b =>
                {
                    b.HasOne("PlatformAPI.Models.Users.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.HasOne("PlatformAPI.Models.Users.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("PlatformAPI.Models.Recipe.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredient")
                        .IsRequired();
                });

            modelBuilder.Entity("PlatformAPI.Models.Recipe.Recipe", b =>
                {
                    b.Navigation("UserRecipe")
                        .IsRequired();
                });

            modelBuilder.Entity("PlatformAPI.Models.Recipe.Step", b =>
                {
                    b.Navigation("RecipeStep")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
